### ISSUE TITLE
编辑完消息后 点击发送后没有反应

### ISSUE THREAD

**Issue by wlnxing** [xtaw/LiteLoaderQQNT-Fake-Message#12]
现象录屏: 

https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/77608284/98b14982-537f-46e7-9324-7ef2c877e2fe

版本:

<img width="1046" alt="image" src="https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/77608284/a63766bb-3fa8-4eb2-b139-9c84ab05490a">

平台: mac

**Comment by Vinzelles** [comment]
一样，貌似用不了了

**Comment by xtaw** [comment]
请认真阅读 README.md 与相关 issues，该插件依赖于第三方API网站，无法保证稳定性，如无法使用可等待或自行搭建API
