### ISSUE TITLE
伪造消息按钮未正常显示

### ISSUE THREAD

**Issue by QingFeng-awa** [xtaw/LiteLoaderQQNT-Fake-Message#13]
### QQNT版本
9.9.9-23424
### LiteLoaderQQNT版本
1.1.1
### 运行环境
Windows11 23H2
### 期望的结果
正常显示在输入框工具栏中。
### 实际的结果
未显示。
### 补充说明
这可能是因为与[轻量工具箱](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools)的精简输入框功能发生了冲突。
在LiteLoaderQQNT启用伪造消息插件并重启后,轻量工具箱精简输入框功能的底部会出现一个没有文字说明的开关(暂且称空白开关),关闭伪造消息插件并重启后这个空白开关就会消失,因此可以初步断定是伪造插件的精简开关。
但是,即使将空白开关开启,伪造消息的按钮也不会出现在输入框工具栏中,这挺令人匪夷所思的。
在卸载掉[轻量工具箱](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools)后伪造消息插件是可以正常出现并正常使用的。
但是,[轻量工具箱](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools)带来的优秀功能非常多,我想大部分用户不会因为伪造消息插件不能与[轻量工具箱](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools)搭配使用而选择卸载[轻量工具箱](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools)吧。
综上所述,希望作者能够尽快修复这个问题并尽快推送1.0.2版本。

**Comment by xtaw** [comment]
我这里似乎并不能稳定复现该问题，即使将空白开关关闭，按钮也能正常显示。也许可能只是自身实现方式问题？之前的实现方式确实有一点投机取巧，计划最近重写
![QQ截图20240511212837](https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/81631889/50944788-8f91-4c38-8456-7ac04143f0b8)

**Comment by QingFeng-awa** [comment]
### 更新1.0.2之后的反馈
更匪夷所思了
轻量工具箱仍然存在空白按钮,并且仍然无法显示伪造消息按钮……
![image](https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/151742581/661a7ada-0347-4c1f-a4a5-55a4032203ba)
上图是禁用轻量工具箱插件并重启的结果。
![image](https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/151742581/b88461d0-4371-47b8-b64a-e6ba779a7970)
![image](https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/151742581/08a9e316-8fdc-477a-95f3-038197106687)
这是我启用的所有插件。

**Comment by xtaw** [comment]
在我这里没有问题，也许问题是在其他插件上？试试只安装Euphony和FakeMessage能否正常显示

**Comment by Vinzelles** [comment]
> 在我这里没有问题，也许问题是在其他插件上？试试只安装Euphony和FakeMessage能否正常显示

![image](https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/67829622/36860653-2ba8-46cc-989d-808029ff3575)
我也遇到了一样的问题

**Comment by QingFeng-awa** [comment]
> 在我这里没有问题，也许问题是在其他插件上？试试只安装Euphony和FakeMessage能否正常显示

![image](https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/151742581/979309eb-7359-46c9-99f8-0c8e21034d9b)
禁用了除伪造消息和其依赖的所有插件,还是没有显示。

**Comment by QingFeng-awa** [comment]
我之前在轻量工具箱的issues看到过一个[issue](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/issues/198#issue-2229779414),也许能帮到你?
![image](https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/151742581/1d26c943-91f6-441b-9453-c5b72fff046e)

**Comment by xtaw** [comment]
1.0.2更新后与DeepL实现原理不同，不可能是这个原因

**Comment by xtaw** [comment]
> > 在我这里没有问题，也许问题是在其他插件上？试试只安装Euphony和FakeMessage能否正常显示
> 
> ![image](https://private-user-images.githubusercontent.com/67829622/329943942-36860653-2ba8-46cc-989d-808029ff3575.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTEyNjEsIm5iZiI6MTcxNTYxMDk2MSwicGF0aCI6Ii82NzgyOTYyMi8zMjk5NDM5NDItMzY4NjA2NTMtMmJhOC00NmNjLTk4OWQtODA4MDI5ZmYzNTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE0MzYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MjU4ZDdiMmRlMjU1NjFhZTFjMTMxNTljOGM5OWIyNTYyYjk4ZGUyMzRiYmYzYzI3MGU5N2ZhMzQwMjc0MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pwY5Dn_TKMzmJFtdUuXS8aGoODj7aC_6DCEdnCn5UR0) 我也遇到了一样的问题

![{A8E61139-5B96-49fc-BEBF-FC4C85FC4465}](https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/81631889/64818a94-480c-4e3f-abda-2aa0d230032b)
按照完全一样的配置，仍然无法复现该 bug

**Comment by xtaw** [comment]
问题已找到，原因是 **Euphony** 依赖版本过低，请从 github 重新下载并安装 **Euphony**，更新至最新版本

**Comment by Vinzelles** [comment]
> 问题已找到，原因是 **Euphony** 依赖版本过低，请从 github 重新下载并安装 **Euphony**，更新至最新版本

谢谢，更新 Euphony 后按钮成功出现，不过消息依然发送不出去。。

**Comment by QingFeng-awa** [comment]
重装Euphony后恢复正常了。
老实说,我还真没想到是依赖的问题……
_咱实在不行给Euphony仓库推送Releases吧_

**Comment by xtaw** [comment]
> > 问题已找到，原因是 **Euphony** 依赖版本过低，请从 github 重新下载并安装 **Euphony**，更新至最新版本
> 
> 谢谢，更新 Euphony 后按钮成功出现，不过消息依然发送不出去。。

消息这个问题只能随缘看那个API能不能用了，或者自己搭建
