### ISSUE TITLE
更新1.0.2后，liteloader直接失效

### ISSUE THREAD

**Issue by VAHua** [xtaw/LiteLoaderQQNT-Fake-Message#14]
![image](https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/129832780/8b9dd199-25a3-4bd7-8b93-91094e64e267)
删除此插件后恢复正常

**Comment by xtaw** [comment]
请提供插件列表和版本信息，以及尝试重新下载并安装Euphony依赖

**Comment by RinTenicol** [comment]
相同问题，安装1.0.2后LiteLoader失效。
尝试过安装昨天新发的Euphony依赖，依旧无效。
降级到1.0.1则安装成功。
图为安装之前的插件列表，还有个LLAPI。
![](https://tenicol.oss-cn-shanghai.aliyuncs.com/website/202405182040349.png)
下图为安装1.0.2后
![](https://tenicol.oss-cn-shanghai.aliyuncs.com/website/202405182045722.png)

**Comment by xtaw** [comment]
渲染器进程有报错信息吗

**Comment by RinTenicol** [comment]
> 渲染器进程有报错信息吗

![](https://tenicol.oss-cn-shanghai.aliyuncs.com/website/202405182104350.png)
![](https://tenicol.oss-cn-shanghai.aliyuncs.com/website/202405182101455.png)

**Comment by xtaw** [comment]
> > 渲染器进程有报错信息吗
> 
> ![](https://camo.githubusercontent.com/3a56f14af5bb894dec6d596672d5b6f5680da1301af88e004f0c678c83ca5957/68747470733a2f2f74656e69636f6c2e6f73732d636e2d7368616e676861692e616c6979756e63732e636f6d2f776562736974652f3230323430353138323130343335302e706e67) ![](https://camo.githubusercontent.com/62b26effb593e24b4bb1b434926dfad5bac09291a219902ce560b816155309fa/68747470733a2f2f74656e69636f6c2e6f73732d636e2d7368616e676861692e616c6979756e63732e636f6d2f776562736974652f3230323430353138323130313435352e706e67)

![{00FBB53D-6481-4977-BD87-581498D71C57}](https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/81631889/db3b30d2-40fd-4cea-ae61-3405328f63b7)
看上去你并没有正确安装 **Euphony** 依赖？请提供插件目录结构

**Comment by RinTenicol** [comment]
> > > 渲染器进程有报错信息吗
> > 
> > 
> > ![](https://camo.githubusercontent.com/3a56f14af5bb894dec6d596672d5b6f5680da1301af88e004f0c678c83ca5957/68747470733a2f2f74656e69636f6c2e6f73732d636e2d7368616e676861692e616c6979756e63732e636f6d2f776562736974652f3230323430353138323130343335302e706e67) ![](https://camo.githubusercontent.com/62b26effb593e24b4bb1b434926dfad5bac09291a219902ce560b816155309fa/68747470733a2f2f74656e69636f6c2e6f73732d636e2d7368616e676861692e616c6979756e63732e636f6d2f776562736974652f3230323430353138323130313435352e706e67)
> 
> ![{00FBB53D-6481-4977-BD87-581498D71C57}](https://private-user-images.githubusercontent.com/81631889/331802693-db3b30d2-40fd-4cea-ae61-3405328f63b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMzg0MDEsIm5iZiI6MTcxNjAzODEwMSwicGF0aCI6Ii84MTYzMTg4OS8zMzE4MDI2OTMtZGIzYjMwZDItNDBmZC00Y2VhLWFlNjEtMzQwNTMyOGY2M2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDEzMTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NThlMjVhY2FlZGI4OGNlZjAxYTI2ZmY1MjczNzFjM2I2NzQwNjllN2I2YTM1Y2M0YTBmNTI5MmMyYTgyMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fGFBY8Pac-Jt8Se5iuLLO0f9g_BNKL9adZ-YScWUiiE) 看上去你并没有正确安装 **Euphony** 依赖？请提供插件目录结构

与1.0.1一样的安装方式
![](https://tenicol.oss-cn-shanghai.aliyuncs.com/website/202405182117015.png)
然后这是1.0.1的log
![](https://tenicol.oss-cn-shanghai.aliyuncs.com/website/202405182118065.png)

**Comment by xtaw** [comment]
![QQ截图20240518212121](https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/81631889/d97f0489-9e59-4d4d-a054-e74232df4f96)
也许你并没有**安装** **Euphony** 插件？

**Comment by RinTenicol** [comment]
> ![QQ截图20240518212121](https://private-user-images.githubusercontent.com/81631889/331804057-d97f0489-9e59-4d4d-a054-e74232df4f96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMzg5NzUsIm5iZiI6MTcxNjAzODY3NSwicGF0aCI6Ii84MTYzMTg4OS8zMzE4MDQwNTctZDk3ZjA0ODktOWU1OS00ZDRkLWEwNTQtZTc0MjMyZGY0Zjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDEzMjQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MTdhZDAwYTFjMzU2N2M4OWQ0MWM4YTY5YTNiYmQzNWYyNDk1ZjQzNTliNzVmMjA5MGMzYWUyYzlmMzQ2NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GFNTMPceFE1Vw125i-M4od5sl1p1ZdIqtzRrn7eVsX8) 也许你并没有**安装** **Euphony** 插件？

确实是我的问题，我直接复制了release压缩包中的Euphony到plugin，但是压缩包中的没有manifest.json。

**Comment by jinghuashang** [comment]
想问问你是如何安装的了 插件文件夹下面你放的文件夹有哪些？
