### ISSUE TITLE
1.0.2更新后按钮消失了

### ISSUE THREAD

**Issue by CNReporter** [xtaw/LiteLoaderQQNT-Fake-Message#15]
还是换了其他地方，我没发现？
![QQ截图20240517165500](https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/36270646/765153d2-6ce5-487f-84f0-0bc4d7b7ab97)

**Comment by xtaw** [comment]
请认真阅读所有 issues，包括 closed issues

**Comment by QingFeng-awa** [comment]
[伪造消息按钮未正常显示 #13](https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/issues/13)
