### ISSUE TITLE
怎么发不出去

### ISSUE THREAD

**Issue by yuhuan1126** [xtaw/LiteLoaderQQNT-Fake-Message#2]
装了依赖LLAPI 但是编辑好后发不出去

https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/87590951/13d01e5d-6f31-4911-9b28-6a1058a24e30

**Comment by xtaw** [comment]
公共API经常性会死，可以等待恢复或自行搭建API

**Comment by yuhuan1126** [comment]
> 公共API经常性会死，可以等待恢复或自行搭建API

怎么搭建api /kel

**Comment by xtaw** [comment]
就是接受http请求并上传聊天记录至qq服务器，获取resId，返回构建好的json，具体没实现过，感觉比较麻烦，一般用公共的API也就够了，想搭建或许可以参考https://github.com/LagrangeDev/Lagrange.Core协议实现
