### ISSUE TITLE
未知原因导致功能失效

### ISSUE THREAD

**Issue by yfy-dodo939** [xtaw/LiteLoaderQQNT-Fake-Message#8]
发送出去后本机显示“[暂不支持该消息类型，请用手机 QQ 查看]”

已经尝试过关闭其余所有插件（除了LLAPI依赖）

但是别人包括我自己的设备都不能看到消息
以下是我安装的插件和liteloader的版本，我确保已经安装了LLAPI依赖
![image](https://github.com/xtaw/LiteLoaderQQNT-Fake-Message/assets/148300042/e9f2008b-0daa-4ea3-9263-54f8983291a8)

**Comment by XMJjs** [comment]
我查看了源代码，发现api站点无法连接

**Comment by 1592363624** [comment]
+1

**Comment by AnsonGames** [comment]
遇到同样问题

**Comment by CNO501** [comment]
不会是api炸了吧...

**Comment by yfy-dodo939** [comment]
好像是公共 api 炸了🤔

**Comment by happytbs** [comment]
而且加载信息还会出现问题

**Comment by RemZer0** [comment]
+1

**Comment by CNO501** [comment]
找到这个api的官网了，各位佬可以看看qwq
https://api.xn--7gqa009h.top/doc/wzlt.html

**Comment by CNO501** [comment]
等等？可以用了！
